// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using UrnaDigital.DataContext;

#nullable disable

namespace UrnaDigital.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20231205200655_first-migration")]
    partial class firstmigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("UrnaDigital.Models.FuncionarioModel", b =>
                {
                    b.Property<int>("IdFuncionario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdFuncionario"));

                    b.Property<int>("Matricula")
                        .HasColumnType("int");

                    b.Property<string>("NomeFuncionario")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdFuncionario");

                    b.ToTable("Funcionarios");
                });

            modelBuilder.Entity("UrnaDigital.Models.RestaurantesModel", b =>
                {
                    b.Property<int>("IdRestaurante")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdRestaurante"));

                    b.Property<DateTime?>("EscolhidoEm")
                        .HasColumnType("datetime2");

                    b.Property<string>("NomeRestaurante")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdRestaurante");

                    b.ToTable("Restaurantes");
                });

            modelBuilder.Entity("UrnaDigital.Models.VotacaoModel", b =>
                {
                    b.Property<int>("IdVotacao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdVotacao"));

                    b.Property<DateTime>("DtVotacao")
                        .HasColumnType("datetime2");

                    b.Property<int>("FuncionarioIdFuncionario")
                        .HasColumnType("int");

                    b.Property<int>("IdFuncionario")
                        .HasColumnType("int");

                    b.Property<int>("IdRestaurante")
                        .HasColumnType("int");

                    b.Property<int>("RestaurantesIdRestaurante")
                        .HasColumnType("int");

                    b.HasKey("IdVotacao");

                    b.HasIndex("FuncionarioIdFuncionario");

                    b.HasIndex("RestaurantesIdRestaurante");

                    b.ToTable("Votacao");
                });

            modelBuilder.Entity("UrnaDigital.Models.VotacaoModel", b =>
                {
                    b.HasOne("UrnaDigital.Models.FuncionarioModel", "Funcionario")
                        .WithMany()
                        .HasForeignKey("FuncionarioIdFuncionario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("UrnaDigital.Models.RestaurantesModel", "Restaurantes")
                        .WithMany()
                        .HasForeignKey("RestaurantesIdRestaurante")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Funcionario");

                    b.Navigation("Restaurantes");
                });
#pragma warning restore 612, 618
        }
    }
}
